Repository ethereumjs/ethereumjs-util, pull requests merged in 2020-10, with the labels that each got.

#275 Add Account class
  CHANGELOG.md
  README.md
  docs/README.md
  docs/classes/_account_.account.md
  docs/interfaces/_account_.accountdata.md
  docs/interfaces/_types_.transformabletobuffer.md
  docs/modules/__types_ethjs_util_index_.md
  docs/modules/_account_.md
  docs/modules/_externals_.md
  docs/modules/_hash_.md
  docs/modules/_helpers_.md
  docs/modules/_types_.md
  package.json
  src/account.ts
  src/helpers.ts
  src/index.ts
  src/types.ts
  test/account.spec.ts
  typedoc.js
Labels: PR state: needs review, type: feature

#277 Add `toBuffer()` method to Address, make `toBuffer()` function convert TransformableToBuffer
  CHANGELOG.md
  src/address.ts
  src/bytes.ts
  src/types.ts
  test/address.spec.ts
  test/bytes.spec.ts
Labels: type: feature

#278 New release v7.0.6
  CHANGELOG.md
  docs/classes/_account_.account.md
  docs/classes/_address_.address.md
  docs/interfaces/_types_.transformabletoarray.md
  docs/interfaces/_types_.transformabletobuffer.md
  docs/modules/_account_.md
  docs/modules/_bytes_.md
  docs/modules/_helpers_.md
  docs/modules/_types_.md
  package.json
Labels: PR state: needs review

#279 Update Account.isEmpty to be EIP-161 compliant / New v7.0.7 Release
  CHANGELOG.md
  package.json
  src/account.ts
  src/types.ts
Labels: PR state: needs review
