Repository ethereumjs/ethereumjs-util, pull requests merged in 2021-02, with the labels that each got.

#287 Handle signatures for chainIds greater than 110
  src/signature.ts
  test/signature.spec.ts
Labels: prio: P3 important, type: bug

#288 New Release v7.0.8
  CHANGELOG.md
  package.json
Labels: PR state: needs review, type: release

#289 Upgrade to ethereumjs-config v2
  .eslintrc.js
  .github/workflows/build.yml
  README.md
  codecov.yml
  karma.conf.js
  package.json
  prettier.config.js
  src/account.ts
  src/address.ts
  src/bytes.ts
  src/constants.ts
  src/hash.ts
  src/object.ts
  src/signature.ts
  src/types.ts
  test/account.spec.ts
  test/address.spec.ts
  test/bytes.spec.ts
  test/constants.spec.ts
  test/externals.spec.ts
  test/hash.spec.ts
  test/object.spec.ts
  test/signature.spec.ts
  tsconfig.json
  tsconfig.prod.json
  tslint.json
Labels: PR state: needs review
